version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: esports
      POSTGRES_PASSWORD: esports123
      POSTGRES_DB: esports_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

volumes:
  postgres_data: